version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "${TaskDefinitionArn}"
        LoadBalancerInfo:
          ContainerName: "wildrydes-container"
          ContainerPort: 80

